services:
  redis:
    image: redis:latest
    container_name: redis-game
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  fastapi:
    build: .
    container_name: fastapi-game
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  redis_data:
